# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-testnet-sepolia        # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"
#     - chain-name: ethereum-mainnet                # Required if your workflow interacts with this chain
#       url: "<select your own rpc url>"

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: base-testnet-sepolia
      url: https://sepolia.base.org
    # Alternative RPC providers:
    # - chain-name: base-testnet-sepolia
    #   url: https://base-sepolia.g.alchemy.com/v2/YOUR_API_KEY
    # - chain-name: base-testnet-sepolia
    #   url: https://base-sepolia.infura.io/v3/YOUR_PROJECT_ID

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: base-testnet-sepolia
      url: https://sepolia.base.org
